import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    tutorial: [{type: "autogenerated", dirName: "tutorial"}],
    reference: [{type: "autogenerated", dirName: "reference"}]
};

export default sidebars;
